name: Send Mastodon Message

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Send toot to Mastodon
      id: mastodon
      uses: cbrgm/mastodon-github-action@v2
      with:
        message: |
          #Mastodon these days really has some early twitter vibes!
          Really cool too see that it gets so much attention lately!
        visibility: "public" # default: public
        access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }} # access token
        url: ${{ secrets.MASTODON_URL }} # https://example.social
