name: Send Mastodon Message

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Send toot to Mastodon
      id: mastodon
      uses: cbrgm/mastodon-github-action@main
      with:
        message: "Hello from GitHub Actions!"
        visibility: "private" # default: public
        access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }} # access token
        url: ${{ secrets.MASTODON_URL }} # https://example.social
